### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by rimmesbe** [daisyhuicoding/prj-rev-bwfs-dasmoto#5]
Grade: Exceeds expectations

Summary: Really good job here, the code was organized and efficient. Not much to comment on here, just a couple little tweaks here and there. Be prepared to lean on classes a lot more heavily as projects increase in size and complexity. If your interested in learning some professional level naming conventions for css there a many conventions out there. Here is a link to BEM style that also lists a bunch of the other popular ones. http://getbem.com/introduction/

**Comment by daisyhuicoding** [comment]
Thanks for the resource and comments.
